### ISSUE TITLE
REST: User

### ISSUE THREAD

**Issue by TimThu** [AlexMeissner/DungeonsAndDragons5e#18]
**Model:**
```json
{
   ID: number,
   Name: string
}
```

**GET:**
GetAll
_URL:_
/users
_Response:_ All Model Instances

**GET:**
GetById
_URL:_
/users/<id>
_Response:_ Model Instance with specific ID

**POST:**
Login
_URL:_
/users/login
_Body:_
```json
{
   Name: string,
   Password: string
}
```
_Response:_ Model

**POST:**
Register (create-like)
_URL:_
/users/register
_Body:_
```json
{
   Name: string,
   Password: string
}
```
_Response:_ Model

**PUT:**
Change username
_URL:_
/users/<id>
_Body:_ Model
_Response:_ Model

**DELETE:**
DeleteById
_URL:_
/users/<id>
_Response:_ 
```json
{
   count: 0|1
}
```

**Comment by AlexMeissner** [comment]
https://github.com/AlexMeissner/DungeonsAndDragons5e/commit/2c90c5240e8a6c50923913635cb643806057b74a
