### ISSUE TITLE
REST: UserCampaignMapping

### ISSUE THREAD

**Issue by TimThu** [AlexMeissner/DungeonsAndDragons5e#19]
**Model:**
```json
{
    ID: number,
    UserID: number,
    CampaignID: number,
    IsGameMaster: boolean
}
```

**GET:**
Campaigns für User
_URL:_
/userCampaignMapping?userID=<id>
_Response:_ Model

**GET:**
User einer Campaign
_URL:_
/userCampaignMapping?campaignID=<id>
_Response:_ Model

**POST:**
Nutzer einer Campaign hinzufügen
_URL:_
/userCampaignMapping
_Body:_ Model
_Response:_ Model

**DELETE:**
Nutzer aus Campaign entfernen
_URL:_
/userCampaignMapping/<id>
_Response:_ 
```json
{
   count: 0 | 1
}
```

**Comment by AlexMeissner** [comment]
[1d1947282e484eac09ceaddd1e7aa3b4904d086f](https://github.com/AlexMeissner/DungeonsAndDragons5e/commit/1d1947282e484eac09ceaddd1e7aa3b4904d086f)
