### ISSUE TITLE
REST: Campaign

### ISSUE THREAD

**Issue by TimThu** [AlexMeissner/DungeonsAndDragons5e#20]
**Model:**
```json
{
    ID: number,
    Name: string,
    PreviewImage: string
}
```

**GET:**
GetById
_URL:_
/Campaigns/<id>
_Response:_ Model

**POST:**
Create a Campaign
_URL:_
/Campaigns
_Body:_ Model
_Response:_ Model

**PATCH:**
Patch single attributes
_URL:_
/Campaigns/<id>?<key>=<value>
_Body:_ Model
_Response:_ Model

**DELETE:**
DeleteById
_URL:_
/Campaigns/<id>
_Response:_ 
```json
{
   count: 0 | 1
}
```

**Comment by AlexMeissner** [comment]
https://github.com/AlexMeissner/DungeonsAndDragons5e/commit/9f052c4260f65ef2022f4d15000be9e2e2bc648f
